// DEFAULT TYPE
export interface IAction {
  type: string;
}

export type InferValueTypes<T> = T extends { [key: string]: infer U }
  ? U
  : never;

export const DOWNLAOD_LIST_REPOS = "DOWNLOAD_LIST_REPOS";
export const DOWNLOAD_LIST_REPOS_SUCCESS = "DOWNLOAD_LIST_REPOS_SUCCESS";
export const DOWNLOAD_LIST_REPOS_FAILED = "DOWNLOAD_LIST_REPOS_FAILED";

export const DOWNLOAD_REPOS_DATA = "DOWNLOAD_REPOS_DATA";
export const DOWNLOAD_REPOS_DATA_SUCCESS = "DOWNLOAD_REPOS_DATA_SUCCESS";
export const DOWNLOAD_REPOS_DATA_FAILED = "DOWNLOAD_REPOS_DATA_FAILED";

export const DOWNLOAD_REPOS_LANGUAGES = "DOWNLOAD_REPOS_LANGUAGES";
export const DOWNLOAD_REPOS_LANGUAGES_SUCCESS =
  "DOWNLOAD_REPOS_LANGUAGES_SUCCESS";
export const DOWNLOAD_REPOS_LANGUAGES_FAILED =
  "DOWNLOAD_REPOS_LANGUAGES_FAILED";

export const DOWNLOAD_REPOS_CONTRIBUTORS = "DOWNLOAD_REPOS_CONTRIBUTORS";
export const DOWNLOAD_REPOS_CONTRIBUTORS_SUCCESS =
  "DOWNLOAD_REPOS_CONTRIBUTORS_SUCCESS";
export const DOWNLOAD_REPOS_CONTRIBUTORS_FAILED =
  "DOWNLOAD_REPOS_CONTRIBUTORS_FAILED";

export const SAVE_MAIN_TO_LOCAL = "SAVE_MAIN_TO_LOCAL";
export const SAVE_MAIN_TO_LOCAL_SUCCESS = "SAVE_MAIN_TO_LOCAL_SUCCESS";
export const SAVE_MAIN_TO_LOCAL_FAILED = "SAVE_MAIN_TO_LOCAL_FAILED";

export const LOAD_MAIN_FROM_LOCAL = "LOAD_MAIN_FROM_LOCAL";
export const LOAD_MAIN_FROM_LOCAL_SUCCESS = "LOAD_MAIN_FROM_LOCAL_SUCCESS";
export const LOAD_MAIN_FROM_LOCAL_FAILED = "LOAD_MAIN_FROM_LOCAL_FAILED";

export const CHANGE_CURR_PAGE = "CHANGE_CURR_PAGE";
export const CHANGE_SEARCH_STRING = "CHANGE_SEARCH_STRING";

export const CHANGE_MAX_COUNT_REPOS = "CAHNGE_MAX_COUNT_REPOS";
